apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: default
spec:
  containers:
    - name: debug-container
      image: alpine
      command: ["sh", "-c", "while true; do sleep 30; done"]
      stdin: true
      tty: true
