# -*- mode: ruby -*-
# vi: set ft=ruby :

# Create 4 VM using VirtualBox Hypervisor

vm_os = "debian/bookworm64" 
vm_memory = 2048
vm_cpus = 2
k8s_master_ip = 10
host_only_network = "VirtualBox Host-Only Ethernet Adapter"
worker_nodes = 3

Vagrant.configure("2") do |config|
  config.vm.define "k8s-master" , primary: true do |master|
    master.vm.box = vm_os
    master.vm.network "private_network", ip: "192.168.56.#{k8s_master_ip}", name: host_only_network
    master.vm.hostname = "kube0"

    master.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", vm_memory]
      vb.customize ["modifyvm", :id, "--cpus", vm_cpus]
    end

    master.vm.provision "shell", path: "provision.sh"
  end

  (1..worker_nodes).each do |i|
    config.vm.define "k8s-worker#{i}" do |worker|
      worker.vm.box = vm_os
      worker.vm.network "private_network", ip: "192.168.56.#{k8s_master_ip + i}", name: host_only_network
      worker.vm.hostname = "kube#{i}"

      worker.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", vm_memory]
        vb.customize ["modifyvm", :id, "--cpus", vm_cpus]
      end

      worker.vm.provision "shell", path: "provision.sh"
    end
  end
end
