destroy_mode: false

sys_kernel_modules:
  - overlay
  - br_netfilter

docker_gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_gpg_path: "/etc/apt/keyrings/docker.asc"
docker_repo_url: "https://download.docker.com/linux/ubuntu"

k8s_gpg_url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
k8s_gpg_path: "/etc/apt/keyrings/kubernetes-archive-keyring.asc"
k8s_repo_url: "https://apt.kubernetes.io"
k8s_distribution_release: "kubernetes-xenial"
k8s_packages:
  - kubeadm
  - kubelet
