---
destroy_mode: false
k8s_packages:
  # This package is optional, it serves to instruct the API Server commands
  # but it can be installed in any host capable of reach the k8s cluster
  # it could be your personal computer
  # I will install it on the control nodes for having an extra point
  - kubectl
  - kubeadm
  - kubelet
calico_conf_url: "https://raw.githubusercontent.com/projectcalico/calico/master/manifests/calico.yaml"
k8s_install_files_path: "/root/k8s_install_files"
k8s_address_range: "193.10.0.0/16"
# Change this depending on your virtual machine configuration
control_node_ip_address: "192.168.100.4"
