apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: replicated-hello
  name: replicated-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: replicated-hello
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: replicated-hello
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:2.0
        name: hello-app
        resources: {}
status: {}
