---
- name: Restart containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted

- name: Disable swap
  ansible.builtin.command:
    cmd: swapoff -a

- name: Enable swap
  ansible.builtin.command:
    cmd: swapon -a
