---
###############################################################################
# Change this depending on your virtual machine configuration
control_node_ip_address: "192.168.56.10"
k8s_address_range: "193.10.0.0/16"

###############################################################################
# Optional configuration
destroy_mode: false

# The version and the checksum can be updated here
# https://github.com/containerd/nerdctl/releases
nerdctl_version: "1.7.2"
nerdctl_checksum: "sha256:aed7d33d645bfb97c8df978d952a1e1f7e02b0b3ed2c0089ee4285af7f8f971b"

# Set this mode to true if you are using Vagrant
# or the reboot steps will fail
vagrant_mode: true

vagrant_dir: "../vagrant"

k8s_packages:
  - kubectl
  - kubeadm
  - kubelet

calico_conf_url: "https://raw.githubusercontent.com/projectcalico/calico/refs/heads/release-v3.29/manifests/calico.yaml"
flannel_version: "0.26.1"
flannel_conf_url: "https://github.com/flannel-io/flannel/releases/download/v{{ flannel_version }}/kube-flannel.yml"

k8s_install_files_path: "/root/k8s_install_files"

sys_kernel_modules:
  - overlay
  - br_netfilter

docker_gpg_url: "https://download.docker.com/linux/{{ linux_distribution }}/gpg"

docker_gpg_path: "/etc/apt/keyrings/docker.asc"

docker_repo_url: "https://download.docker.com/linux/{{ linux_distribution }}"

k8s_gpg_url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"

k8s_release_key_path: "/tmp/k8s-release.key"

k8s_gpg_path: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"

k8s_repo_url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/"
