---
###############################################################################
# Change this depending on your virtual machine configuration
control_node_ip_address: "192.168.100.4"
k8s_address_range: "193.10.0.0/16"

###############################################################################
# Optional configuration
destroy_mode: false

# The version and the checksum can be updated here
# https://github.com/containerd/nerdctl/releases
nerdctl_version: "1.7.2"
nerdctl_checksum: "sha256:aed7d33d645bfb97c8df978d952a1e1f7e02b0b3ed2c0089ee4285af7f8f971b"

k8s_packages:
  - kubectl
  - kubeadm
  - kubelet

calico_conf_url: "https://raw.githubusercontent.com/projectcalico/calico/master/manifests/calico.yaml"

k8s_install_files_path: "/root/k8s_install_files"

sys_kernel_modules:
  - overlay
  - br_netfilter

docker_gpg_url: "https://download.docker.com/linux/ubuntu/gpg"

docker_gpg_path: "/etc/apt/keyrings/docker.asc"

docker_repo_url: "https://download.docker.com/linux/ubuntu"

k8s_gpg_url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"

k8s_gpg_path: "/etc/apt/keyrings/kubernetes-archive-keyring.asc"

k8s_repo_url: "https://apt.kubernetes.io"

k8s_distribution_release: "kubernetes-xenial"
