---
- name: Determine system architecture
  register: sys_architecture
  ansible.builtin.command:
    cmd: "dpkg --print-architecture"
  changed_when: sys_architecture.rc != 0

- name: Set k8s facts pre installation
  ansible.builtin.set_fact:
    sys_architecture: "{{ sys_architecture.stdout }}"

- name: Download k8s GPG key
  ansible.builtin.get_url:
    url: "{{ k8s_gpg_url }}"
    dest: "{{ k8s_gpg_path }}"
    mode: '0644'
    force: true

- name: Add k8s Official apt repository
  ansible.builtin.apt_repository:
    filename: k8s
    repo: "deb [arch={{ sys_architecture }} signed-by={{ k8s_gpg_path }}] {{ k8s_repo_url }} {{ k8s_distribution_release }} main"
    mode: '0644'
    state: "{{ 'absent' if destroy_mode else 'present' }}"
